export type Category =
  | "Frontend Development"
  | "Backend Development"
  | "CSS"
  | "CSS Framework"
  | "Core Web Vitals"
  | "UI Kit"
  | "CSS Trends"
  | "Headless CMS"
  | "Programming Languages"
  | "APIs"
  | "Sharing Experience"
  | "Podcast"
  | "Databases"
  | "Data Structure and Algorithm"
  | "Mock Interview"
  | "DevOps"
  | "Testing"
  | "Cloud"
  | "Security"
  | "Mobile"
  | "Game Development"
  | "AI"
  | "Machine Learning"
  | "Data Science"
  | "Big Data"
  | "IoT"
  | "Blockchain"
  | "AR/VR"
  | "Project Management"
  | "Version Control"
  | "CI/CD"
  | "Containerization"
  | "Microservices"
  | "Serverless"
  | "WebAssembly"
  | "Performance"
  | "Code Quality"
  | "Architecture"
  | "Design Patterns"
  | "UX"
  | "Accessibility"
  | "Analytics"
  | "Networking"
  | "Operating Systems"
  | "Scripting"
  | "Automation"
  | "Embedded Systems"
  | "Quantum Computing"
  | "Edge Computing"
  | "Robotics"
  | "Ethical Hacking"
  | "Technical Writing"
  | "Community Engagement"
  | "Open Source"
  | "Remote Work"
  | "Agile"
  | "Project Based Learning (PBL)"
  | "JavaScript"
  | "React"
  | "Go"
  | "Vue"
  | "Next.js"
  | "Remix"
  | "GitLab"
  | "GitHub"
  | "Git"
  | "TypeScript"
  | "Python"
  | "Java"
  | "C#"
  | "Ruby"
  | "PHP"
  | "Swift"
  | "Kotlin"
  | "Rust"
  | "Dart"
  | "Flutter"
  | "Android"
  | "iOS"
  | "GraphQL"
  | "REST"
  | "Web Development"
  | "Desktop Development"
  | "Electron"
  | "TensorFlow"
  | "PyTorch"
  | "Docker"
  | "Kubernetes"
  | "Ansible"
  | "Terraform"
  | "Jenkins"
  | "Travis CI"
  | "CircleCI"
  | "Firebase"
  | "AWS"
  | "Azure"
  | "Google Cloud"
  | "Salesforce"
  | "SAP"
  | "Oracle"
  | "SaaS"
  | "PaaS"
  | "IaaS"
  | "NoSQL"
  | "SQL"
  | "MongoDB"
  | "PostgreSQL"
  | "MySQL"
  | "SQLite"
  | "Redis"
  | "Kafka"
  | "Elasticsearch";
